name: COM-Warfare
version: 2.14.3
description: Call of Duty Multiplayer recreated for use in Minecraft!
author: Mr_Rhetorical
website: https://www.spigotmc.org/resources/21895/

main: com.rhetorical.cod.ComWarfare
api-version: 1.13

softdepend: [Multiverse-Core, CrackShot, QualityArmory, ProtocolLib]

commands:
  cod:
    aliases: [comr, com, war]
    description: Base command for COM-Warfare.
    usage: /<command>